stages:
  - build

before_script:
  - apt-get update
  - apt-get -y install libreoffice

build:
  stage: build
  tags:
    - docker
  image: maven:3.3-jdk-8
  script:
    - mvn clean test
  artifacts:
    paths:
      - /root/.m2/
    expire_in: 1 day

